blueprint:
  name: Set Thermostat Temperature Based on Presence
  description: >
    This blueprint sets the temperature of a thermostat based on the presence
    of people in the house.
  domain: automation
  input:
    thermostat_entity:
      name: Thermostat entity
      description: The entity_id of the thermostat to control.
      selector:
        entity:
          domain: climate
    temperature_home:
      name: Temperature when home (in Fahrenheit)
      description: The temperature to set the thermostat to when someone is home.
      default: 76
      selector:
        number:
          min: 50
          max: 90
          unit_of_measurement: "°F"
          mode: slider
    temperature_away:
      name: Temperature when away (in Fahrenheit)
      description: The temperature to set the thermostat to when no one is home.
      default: 80
      selector:
        number:
          min: 50
          max: 90
          unit_of_measurement: "°F"
          mode: slider
    proximity_sensor_entity:
      name: Proximity sensor entity
      description: The entity_id of the proximity sensor to detect presence.
      selector:
        entity:
          domain: binary_sensor
          device_class: proximity

  trigger:
    - platform: state
      entity_id: !input proximity_sensor_entity
      from: "off"
      to: "on"
    - platform: state
      entity_id: !input proximity_sensor_entity
      from: "on"
      to: "off"

  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: !input proximity_sensor_entity
              state: "on"
          sequence:
            - service: climate.set_temperature
              data:
                entity_id: !input thermostat_entity
                temperature: !input temperature_home
        - conditions:
            - condition: state
              entity_id: !input proximity_sensor_entity
              state: "off"
          sequence:
            - delay: "00:05:00"
            - condition: state
              entity_id: !input proximity_sensor_entity
              state: "off"
            - service: climate.set_temperature
              data:
                entity_id: !input thermostat_entity
                temperature: !input temperature_away
      default:
        - service: climate.set_temperature
          data:
            entity_id: !input thermostat_entity
            temperature: !input temperature_away
